DATA_DIRECTORY_SOURCE = 'D:/Datasets/COTS_GoPro_1080_v3'
SOURCE_CATEGORY_ID = 0
TARGET_CATEGORY_ID = 1
DATA_DIRECTORY_TARGET = 'D:/Datasets/AIMS_SEP_2022'
DATA_DIRECTORY_TARGET2 = 'D:/Datasets/AIMS_OCT_2022'